---
name: 运维审批
option:
  - describe: 运维审批人
    name: opapprover
    type: selectx
    value: ""
    command: "c3mc-bpm-optionx-opapprover"

template_argv:
  approver: ${opapprover}
  title:    "BPM/${_bpmuuid_}/定时操作EC2实例增加实例"
  content:  |
    BPM标题: 定时操作EC2实例增加实例
    BPM地址: ${_caseurl_}

    申请人:${_user_}
    申请理由:${x.note}
  record: 1
