---
name: '业务审批人'
option:
  - describe: 申请理由
    name: note
    type: text
    value: ""

template_argv:
  approver: "vuuidowner(${x.instance_arn}) or vuuidowner(${x.cluster_arn})"
  title:    "BPM/${_bpmuuid_}/资源回收/AWS/elasticache"
  content:  |
    BPM标题: 资源回收/AWS/elasticache
    BPM地址: ${_caseurl_}

    申请人:${_user_}
    申请理由:${x.note}
  record: 1
  relaxed: 1
  submitter: '${_user_}'
